local M = {}

M.resource_prototypes = {"resource", "tree", "simple-entity"}

M.building_prototypes = {
    "accumulator",
    "ammo-turret",
    "arithmetic-combinator",
    "artillery-turret",
    "assembling-machine",
    "beacon",
    "boiler",
    "constant-combinator",
    "container",
    "curved-rail",
    "decider-combinator",
    "electric-energy-interface",
    "electric-pole",
    "electric-turret",
    "fluid-turret",
    "furnace",
    "gate",
    "generator",
    "heat-interface",
    "heat-pipe",
    "infinity-container",
    "infinity-pipe",
    "inserter",
    "lab",
    "lamp",
    "loader",
    "logistic-container",
    "mining-drill",
    "offshore-pump",
    "pipe-to-ground",
    "pipe",
    "power-switch",
    "programmable-speaker",
    "pump",
    "radar",
    "rail-chain-signal",
    "rail-signal",
    "reactor",
    "roboport",
    "rocket-silo",
    "solar-panel",
    "splitter",
    "storage-tank",
    "straight-rail",
    "train-stop",
    "transport-belt",
    "turret",
    "underground-belt",
    "wall"
}

return M
